### ISSUE TITLE
JSONException

### ISSUE THREAD

**Issue by tuhochi** [sysworx/synosync#1]
An exception of class JSONException was not handled.  The application must shut down.

Exception Message: Parse Error: Expecting '{' or '['
Exception Error Number: 1

**Comment by sysworx** [comment]
Hey, sorry but synoSync isnt in development anymore. I dont have a mac or a synolgy nas anymore. But its opensource. I think the webapi of the nas has been changed. 

Which version of DSM are you using?

**Comment by sysworx** [comment]
Maybe i can fix it in a few weeks, i try to get a virtual DSM running. When will synoSync show up this error?
