### ISSUE TITLE
Not compatible with Catalina

### ISSUE THREAD

**Issue by massa007** [sysworx/synosync#2]
Any chance this one gets an update for Catalina in 64-bit? :)

**Comment by sysworx** [comment]
Puh difficult, i dont have a mac or synology anymore. Maybe i can try to compile this old code to 64 bit with old xojo on windows 🤔

**Comment by sysworx** [comment]
So i tried to compile a 64bit but its not possible with xojo in windows...only 32bit. For a 64bit app i need a Mac. 

Sorry :(
